=== drugis/mcda-elicitation-web/schema/problem.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://mcda.drugis.org/problem.json#",
  "title": "MCDA problem schema",
  "description": "MCDA problem schema for uploaded JSON, version 1.4.5",
  "type": "object",
  "required": ["schemaVersion", "criteria", "alternatives", "performanceTable"],
  "properties": {
    "schemaVersion": {
      "description": "The current version of the schema",
      "type": "string"
    },
    "title": {
      "description": "Title of the problem",
      "type": "string"
    },
    "description": {
      "description": "Description of the therapeutic context",
      "type": "string"
    },
    "criteria": {
      "description": "The criteria of the problem",
      "type": "object",
      "minProperties": 2,
      "additionalProperties": {
        "type": "object",
        "required": ["id", "title", "dataSources"],
        "additionalProperties": false,
        "properties": {
          "title": {
            "description": "Title of the criterion",
            "type": "string"
          },
          "id": {
            "description": "Id of the criterion",
            "type": "string"
          },
          "isFavorable": {
            "description": "Is the criterion favorable or not?",
            "type": "boolean"
          },
          "description": {
            "description": "Description of the criterion",
            "type": "string"
          },
          "dataSources": {
            "description": "The source information of the data for the criterion",
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "dataSource.json#"
            }
          }
        }
      }
    },
    "alternatives": {
      "description": "The alternatives of the problem",
      "type": "object",
      "minProperties": 2,
      "additionalProperties": {
        "type": "object",
        "required": ["title", "id"],
        "additionalProperties": false,
        "properties": {
          "title": {
            "description": "Title of the alternative",
            "type": "string"
          },
          "id": {
            "description": "Id of the alternative",
            "type": "string"
          }
        }
      }
    },
    "performanceTable": {
      "description": "The data of the effects table",
      "type": "array",
      "items": {
        "oneOf": [
          {
            "$ref": "relativeEntry.json#"
          },
          {
            "$ref": "absoluteEntry.json#"
          }
        ]
      }
    }
  }
}

=== drugis/mcda-elicitation-web/test/endToEnd/util/allEffectAndDistributionTypes.json
{
  "schemaVersion": "1.4.5",
  "title": "all the things",
  "description": "",
  "criteria": {
    "percentageCriterion": {
      "id": "percentageCriterion",
      "title": "percentages",
      "description": "description",
      "dataSources": [
        {
          "id": "ds1Id",
          "source": "ref",
          "sourceLink": "www.ref.com",
          "uncertainties": "uncertainty",
          "strengthOfEvidence": "strength",
          "unitOfMeasurement": {
            "type": "percentage",
            "label": "%"
          },
          "scale": [0, 100]
        }
      ]
    },
    "decimalCriterion": {
      "id": "decimalCriterion",
      "title": "decimals",
      "description": "description",
      "dataSources": [
        {
          "id": "ds2Id",
          "source": "ref",
          "sourceLink": "www.ref.com",
          "uncertainties": "uncertainty",
          "strengthOfEvidence": "strength",
          "unitOfMeasurement": {
            "type": "decimal",
            "label": ""
          },
          "scale": [0, 1]
        }
      ]
    },
    "customCriterion": {
      "id": "customCriterion",
      "title": "custom",
      "description": "description",
      "dataSources": [
        {
          "id": "ds3Id",
          "source": "ref",
          "sourceLink": "www.ref.com",
          "uncertainties": "uncertainty",
          "strengthOfEvidence": "strength",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          },
          "scale": [null, null]
        }
      ]
    }
  },
  "alternatives": {
    "alt1Id": {
      "id": "alt1Id",
      "title": "alt1"
    },
    "alt2Id": {
      "id": "alt2Id",
      "title": "alt2"
    },
    "alt3Id": {
      "id": "alt3Id",
      "title": "alt3"
    },
    "alt4Id": {
      "id": "alt4Id",
      "title": "alt4"
    },
    "alt5Id": {
      "id": "alt5Id",
      "title": "alt5"
    },
    "alt6Id": {
      "id": "alt6Id",
      "title": "alt6"
    },
    "alt7Id": {
      "id": "alt7Id",
      "title": "alt7"
    }
  },
  "performanceTable": [
    {
      "alternative": "alt1Id",
      "criterion": "percentageCriterion",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.01
        },
        "distribution": {
          "type": "dnorm",
          "parameters": {
            "mu": 0,
            "sigma": 0.005
          }
        }
      }
    },
    {
      "alternative": "alt2Id",
      "criterion": "percentageCriterion",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.01,
          "input": {
            "value": 1,
            "lowerBound": 0,
            "upperBound": 2
          }
        },
        "distribution": {
          "type": "dbeta",
          "parameters": {
            "alpha": 1,
            "beta": 5
          }
        }
      }
    },
    {
      "alternative": "alt3Id",
      "criterion": "percentageCriterion",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.455,
          "input": {
            "lowerBound": 1,
            "upperBound": 90
          }
        },
        "distribution": {
          "type": "dgamma",
          "parameters": {
            "alpha": 1,
            "beta": 5
          }
        }
      }
    },
    {
      "alternative": "alt4Id",
      "criterion": "percentageCriterion",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "exact",
          "value": 0.01
        }
      }
    },
    {
      "alternative": "alt5Id",
      "criterion": "percentageCriterion",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "empty",
          "value": "text me"
        },
        "distribution": {
          "type": "range",
          "parameters": {
            "lowerBound": 0,
            "upperBound": 0.9
          }
        }
      }
    },
    {
      "alternative": "alt6Id",
      "criterion": "percentageCriterion",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "empty"
        }
      }
    },
    {
      "alternative": "alt7Id",
      "criterion": "percentageCriterion",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "empty",
          "value": "text me"
        }
      }
    },
    {
      "alternative": "alt1Id",
      "criterion": "decimalCriterion",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 1
        },
        "distribution": {
          "type": "dnorm",
          "parameters": {
            "mu": 0,
            "sigma": 0.5
          }
        }
      }
    },
    {
      "alternative": "alt2Id",
      "criterion": "decimalCriterion",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.2,
          "input": {
            "value": 0.2,
            "lowerBound": 0.1,
            "upperBound": 0.5
          }
        },
        "distribution": {
          "type": "dbeta",
          "parameters": {
            "alpha": 1,
            "beta": 5
          }
        }
      }
    },
    {
      "alternative": "alt3Id",
      "criterion": "decimalCriterion",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.45,
          "input": {
            "lowerBound": 0,
            "upperBound": 0.9
          }
        },
        "distribution": {
          "type": "dgamma",
          "parameters": {
            "alpha": 1,
            "beta": 5
          }
        }
      }
    },
    {
      "alternative": "alt4Id",
      "criterion": "decimalCriterion",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "exact",
          "value": 1
        }
      }
    },
    {
      "alternative": "alt5Id",
      "criterion": "decimalCriterion",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "empty",
          "value": "text me"
        },
        "distribution": {
          "type": "range",
          "parameters": {
            "lowerBound": 0,
            "upperBound": 0.9
          }
        }
      }
    },
    {
      "alternative": "alt6Id",
      "criterion": "decimalCriterion",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "empty"
        }
      }
    },
    {
      "alternative": "alt7Id",
      "criterion": "decimalCriterion",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "empty",
          "value": "text me"
        }
      }
    },
    {
      "alternative": "alt1Id",
      "criterion": "customCriterion",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 1
        },
        "distribution": {
          "type": "dnorm",
          "parameters": {
            "mu": 0,
            "sigma": 0.5
          }
        }
      }
    },
    {
      "alternative": "alt2Id",
      "criterion": "customCriterion",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 1,
          "input": {
            "value": 1,
            "lowerBound": 0,
            "upperBound": 2
          }
        },
        "distribution": {
          "type": "dbeta",
          "parameters": {
            "alpha": 1,
            "beta": 5
          }
        }
      }
    },
    {
      "alternative": "alt3Id",
      "criterion": "customCriterion",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 45.5,
          "input": {
            "lowerBound": 1,
            "upperBound": 90
          }
        },
        "distribution": {
          "type": "dgamma",
          "parameters": {
            "alpha": 1,
            "beta": 5
          }
        }
      }
    },
    {
      "alternative": "alt4Id",
      "criterion": "customCriterion",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "exact",
          "value": 1
        }
      }
    },
    {
      "alternative": "alt5Id",
      "criterion": "customCriterion",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "empty",
          "value": "text me"
        },
        "distribution": {
          "type": "range",
          "parameters": {
            "lowerBound": 0,
            "upperBound": 90
          }
        }
      }
    },
    {
      "alternative": "alt6Id",
      "criterion": "customCriterion",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "empty"
        }
      }
    },
    {
      "alternative": "alt7Id",
      "criterion": "customCriterion",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "empty"
        },
        "distribution": {
          "type": "empty",
          "value": "text me"
        }
      }
    }
  ]
}

=== drugis/mcda-elicitation-web/test/endToEnd/util/onlyDistributionsProblem.json
{
  "schemaVersion": "1.4.5",
  "title": "only distributions",
  "description": "",
  "criteria": {
    "crit1": {
      "id": "crit1",
      "title": "criterion 1",
      "description": "",
      "dataSources": [
        {
          "id": "ds1",
          "source": "",
          "sourceLink": "",
          "uncertainties": "",
          "strengthOfEvidence": "",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          },
          "scale": [null, null]
        }
      ],
      "isFavorable": true
    },
    "crit2": {
      "id": "crit2",
      "title": "criterion 2",
      "description": "",
      "dataSources": [
        {
          "id": "ds2",
          "source": "",
          "sourceLink": "",
          "uncertainties": "",
          "strengthOfEvidence": "",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          },
          "scale": [null, null]
        }
      ],
      "isFavorable": true
    }
  },
  "alternatives": {
    "alt1": {
      "id": "alt1",
      "title": "alternative 1"
    },
    "alt2": {
      "id": "alt2",
      "title": "alternative 2"
    }
  },
  "performanceTable": [
    {
      "alternative": "alt1",
      "criterion": "crit1",
      "dataSource": "ds1",
      "performance": {
        "distribution": {
          "type": "dnorm",
          "parameters": {
            "mu": 0,
            "sigma": 0.5
          }
        }
      }
    },
    {
      "alternative": "alt2",
      "criterion": "crit1",
      "dataSource": "ds1",
      "performance": {
        "distribution": {
          "type": "dnorm",
          "parameters": {
            "mu": 1,
            "sigma": 0.5
          }
        }
      }
    },
    {
      "alternative": "alt1",
      "criterion": "crit2",
      "dataSource": "ds2",
      "performance": {
        "distribution": {
          "type": "dnorm",
          "parameters": {
            "mu": 2,
            "sigma": 0.5
          }
        }
      }
    },
    {
      "alternative": "alt2",
      "criterion": "crit2",
      "dataSource": "ds2",
      "performance": {
        "distribution": {
          "type": "dnorm",
          "parameters": {
            "mu": 3,
            "sigma": 0.5
          }
        }
      }
    }
  ]
}

=== drugis/mcda-elicitation-web/test/endToEnd/util/onlyEmptyAndText.json
{
  "schemaVersion": "1.4.6",
  "title": "Only text and empty workspace",
  "description": "",
  "criteria": {
    "c1243ed9-c886-4c74-91ac-177c42559c4f": {
      "id": "c1243ed9-c886-4c74-91ac-177c42559c4f",
      "title": "criterion 1",
      "description": "",
      "dataSources": [
        {
          "id": "3e099fa8-2807-4c5f-b822-e709f8bf9827",
          "source": "",
          "sourceLink": "",
          "uncertainties": "",
          "strengthOfEvidence": "",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          },
          "scale": [
            null,
            null
          ]
        }
      ],
      "isFavorable": true
    },
    "7d52c11c-7764-4245-b4e5-a6d346a5ca28": {
      "id": "7d52c11c-7764-4245-b4e5-a6d346a5ca28",
      "title": "criterion 2",
      "description": "",
      "dataSources": [
        {
          "id": "36a00bc7-e4c1-489b-bd2f-c3683350c7a1",
          "source": "",
          "sourceLink": "",
          "uncertainties": "",
          "strengthOfEvidence": "",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          },
          "scale": [
            null,
            null
          ]
        }
      ],
      "isFavorable": true
    }
  },
  "alternatives": {
    "bff93968-e258-4b60-9db2-89e757571460": {
      "id": "bff93968-e258-4b60-9db2-89e757571460",
      "title": "alternative 1"
    },
    "f8280e65-23d4-41d8-a3f7-5c50f4c263ae": {
      "id": "f8280e65-23d4-41d8-a3f7-5c50f4c263ae",
      "title": "alternative 2"
    }
  },
  "performanceTable": [
    {
      "alternative": "bff93968-e258-4b60-9db2-89e757571460",
      "criterion": "c1243ed9-c886-4c74-91ac-177c42559c4f",
      "dataSource": "3e099fa8-2807-4c5f-b822-e709f8bf9827",
      "performance": {
        "effect": {
          "type": "empty"
        }
      }
    },
    {
      "alternative": "f8280e65-23d4-41d8-a3f7-5c50f4c263ae",
      "criterion": "c1243ed9-c886-4c74-91ac-177c42559c4f",
      "dataSource": "3e099fa8-2807-4c5f-b822-e709f8bf9827",
      "performance": {
        "effect": {
          "type": "empty",
          "value": "text cell"
        }
      }
    },
    {
      "alternative": "bff93968-e258-4b60-9db2-89e757571460",
      "criterion": "7d52c11c-7764-4245-b4e5-a6d346a5ca28",
      "dataSource": "36a00bc7-e4c1-489b-bd2f-c3683350c7a1",
      "performance": {
        "effect": {
          "type": "empty"
        }
      }
    },
    {
      "alternative": "f8280e65-23d4-41d8-a3f7-5c50f4c263ae",
      "criterion": "7d52c11c-7764-4245-b4e5-a6d346a5ca28",
      "dataSource": "36a00bc7-e4c1-489b-bd2f-c3683350c7a1",
      "performance": {
        "effect": {
          "type": "empty",
          "value": "more text"
        }
      }
    }
  ]
}

=== drugis/mcda-elicitation-web/test/endToEnd/util/partialValueFunctionTestProblem.json
{
  "schemaVersion": "1.4.5",
  "title": "Test workspace",
  "criteria": {
    "c1": {
      "id": "c1",
      "title": "c1",
      "dataSources": [
        {
          "id": "ds1Id",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          },
          "scale": [null, null],
          "source": "ref1"
        }
      ]
    },
    "c2": {
      "id": "c2",
      "title": "c2",
      "dataSources": [
        {
          "id": "ds2Id",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          },
          "scale": [null, null],
          "source": "ref2"
        }
      ]
    }
  },
  "alternatives": {
    "a1": {
      "id": "a1",
      "title": "a1"
    },
    "a2": {
      "id": "a2",
      "title": "a2"
    }
  },
  "performanceTable": [
    {
      "alternative": "a1",
      "criterion": "c1",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 1
        }
      }
    },
    {
      "alternative": "a2",
      "criterion": "c1",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 2
        }
      }
    },
    {
      "alternative": "a1",
      "criterion": "c2",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 3
        }
      }
    },
    {
      "alternative": "a2",
      "criterion": "c2",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 4
        }
      }
    }
  ]
}

=== drugis/mcda-elicitation-web/test/endToEnd/util/createSubproblemTestProblem.json
{
  "schemaVersion": "1.4.5",
  "title": "Test workspace",
  "criteria": {
    "crit1Id": {
      "id": "crit1Id",
      "title": "c1",
      "dataSources": [
        {
          "id": "ds1Id",
          "scale": [null, null],
          "source": "ref1",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          }
        },
        {
          "id": "deselectionDataSourceId",
          "scale": [null, null],
          "source": "ref2",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          }
        }
      ]
    },
    "crit2Id": {
      "id": "crit2Id",
      "title": "c2",
      "dataSources": [
        {
          "id": "ds2Id",
          "scale": [null, null],
          "source": "ref3",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          }
        }
      ]
    },
    "deselectionCriterionId": {
      "id": "deselectionCriterionId",
      "title": "c3",
      "dataSources": [
        {
          "id": "ds3Id",
          "scale": [null, null],
          "source": "ref4",
          "unitOfMeasurement": {
            "type": "custom",
            "label": ""
          }
        }
      ]
    }
  },
  "alternatives": {
    "alt1Id": {
      "id": "alt1Id",
      "title": "a1"
    },
    "alt2Id": {
      "id": "alt2Id",
      "title": "a2"
    },
    "deselectionAlternativeId": {
      "id": "deselectionAlternativeId",
      "title": "a3"
    }
  },
  "performanceTable": [
    {
      "alternative": "alt1Id",
      "criterion": "crit1Id",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": -100
        }
      }
    },
    {
      "alternative": "alt2Id",
      "criterion": "crit1Id",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 100
        }
      }
    },
    {
      "alternative": "deselectionAlternativeId",
      "criterion": "crit1Id",
      "dataSource": "ds1Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0
        }
      }
    },
    {
      "alternative": "alt1Id",
      "criterion": "crit1Id",
      "dataSource": "deselectionDataSourceId",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0
        }
      }
    },
    {
      "alternative": "alt2Id",
      "criterion": "crit1Id",
      "dataSource": "deselectionDataSourceId",
      "performance": {
        "effect": {
          "type": "empty"
        }
      }
    },
    {
      "alternative": "deselectionAlternativeId",
      "criterion": "crit1Id",
      "dataSource": "deselectionDataSourceId",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0
        }
      }
    },
    {
      "alternative": "alt1Id",
      "criterion": "crit2Id",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": -50.5,
          "input": {
            "lowerBound": -101,
            "upperBound": 0
          }
        }
      }
    },
    {
      "alternative": "alt2Id",
      "criterion": "crit2Id",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0,
          "input": {
            "value": 0,
            "lowerBound": -5,
            "upperBound": 6
          }
        }
      }
    },
    {
      "alternative": "deselectionAlternativeId",
      "criterion": "crit2Id",
      "dataSource": "ds2Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0
        }
      }
    },
    {
      "alternative": "alt1Id",
      "criterion": "deselectionCriterionId",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "empty",
          "value": "text"
        }
      }
    },
    {
      "alternative": "alt2Id",
      "criterion": "deselectionCriterionId",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0
        }
      }
    },
    {
      "alternative": "deselectionAlternativeId",
      "criterion": "deselectionCriterionId",
      "dataSource": "ds3Id",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0
        }
      }
    }
  ]
}

=== drugis/mcda-elicitation-web/examples/regular-examples/getreal.json
{
  "title": "GetReal course LU 4, activity 4.4",
  "description": "Hypothetical new cancer treatment example.",
  "criteria": {
    "OS": {
      "id": "OS",
      "title": "2-year survival",
      "description": "Proportion of patients surviving for 2 years or longer",
      "dataSources": [
        {
          "pvf": {
            "range": [0.45, 0.65],
            "type": "linear",
            "direction": "increasing"
          },
          "scale": [0, 100],
          "id": "dsOS",
          "unitOfMeasurement": {
            "type": "percentage",
            "label": "%"
          }
        }
      ],
      "isFavorable": true
    },
    "severe": {
      "id": "severe",
      "title": "Severe toxicity",
      "description": "Proportion of patients experiencing severe side-effects",
      "dataSources": [
        {
          "pvf": {
            "range": [0, 0.8],
            "type": "linear",
            "direction": "decreasing"
          },
          "scale": [0, 100],
          "id": "dsSevere",
          "unitOfMeasurement": {
            "type": "percentage",
            "label": "%"
          }
        }
      ],
      "isFavorable": false
    },
    "moderate": {
      "id": "moderate",
      "title": "Moderate toxicity",
      "description": "Proportion of patients experiencing long-lasting moderate side-effects",
      "dataSources": [
        {
          "pvf": {
            "range": [0, 0.4],
            "type": "linear",
            "direction": "decreasing"
          },
          "scale": [0, 100],
          "id": "dsModerate",
          "unitOfMeasurement": {
            "type": "percentage",
            "label": "%"
          }
        }
      ],
      "isFavorable": false
    }
  },
  "alternatives": {
    "alt1": {
      "id": "alt1",
      "title": "New treatment"
    },
    "alt2": {
      "id": "alt2",
      "title": "Control"
    }
  },
  "performanceTable": [
    {
      "alternative": "alt1",
      "criterion": "OS",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.6,
          "input": {
            "scale": "percentage",
            "value": 60
          }
        }
      },
      "dataSource": "dsOS"
    },
    {
      "alternative": "alt2",
      "criterion": "OS",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.5,
          "input": {
            "scale": "percentage",
            "value": 50
          }
        }
      },
      "dataSource": "dsOS"
    },
    {
      "alternative": "alt1",
      "criterion": "severe",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.6,
          "input": {
            "scale": "percentage",
            "value": 60
          }
        }
      },
      "dataSource": "dsSevere"
    },
    {
      "alternative": "alt2",
      "criterion": "severe",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.2,
          "input": {
            "scale": "percentage",
            "value": 20
          }
        }
      },
      "dataSource": "dsSevere"
    },
    {
      "alternative": "alt1",
      "criterion": "moderate",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.35,
          "input": {
            "scale": "percentage",
            "value": 35
          }
        }
      },
      "dataSource": "dsModerate"
    },
    {
      "alternative": "alt2",
      "criterion": "moderate",
      "performance": {
        "effect": {
          "type": "exact",
          "value": 0.05,
          "input": {
            "scale": "percentage",
            "value": 5
          }
        }
      },
      "dataSource": "dsModerate"
    }
  ],
  "schemaVersion": "1.4.5"
}
